# Site
name: "jkfran"
title: "Francisco Jiménez Cabrera"
description: "A blog featuring tutorials, ideas, and anything interesting to me."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /
insights: "A7gP_jf0zVamA1Pm"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jkfran:
    name: Francisco Jiménez Cabrera
    display_name: Francisco Jiménez Cabrera
    gravatar: 5fdfe91237cdb6cc5d84b2776ee0b8ab
    email: jkfran@gmail.com
    web: https://jkfran.com/about
    twitter: https://twitter.com/bksfran
    description: "Senior Software Engineer at PolyModels Hub. Passionate about DevOps, MLOps, and building better software."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]
