// PurgeCSS audit configuration
// Run: npm run audit:css
//
// This does NOT modify your CSS files. It compiles SCSS into .audit/,
// scans all HTML templates + JS for class references, and reports
// selectors from your custom SCSS that are never used.

module.exports = {
  // Compiled custom CSS (built by the audit:build-css script)
  css: [".audit/main.css", ".audit/tools.css", ".audit/about.css"],

  // All sources of class references
  content: [
    "_layouts/**/*.html",
    "_includes/**/*.html",
    "_tools/**/*.html",
    "_pages/**/*.{html,md}",
    "_posts/**/*.{html,md}",
    "index.html",
    "assets/js/**/*.js",
  ],

  // Classes added dynamically via JS (innerHTML, classList, etc.)
  // These will never appear in static HTML so PurgeCSS must skip them.
  safelist: {
    standard: [
      // Search modal (lunrsearchengine.js builds entire modal via innerHTML)
      "modal-open",
      "modal",
      "modal-dialog",
      "modal-content",
      "modal-header",
      "modal-body",
      "modal-footer",
      "modal-title",
      "fade",
      "show",
      "d-block",
      "btn-close",
      "close-search",
      "lunrsearchresult",
      "shadow-lg",
      "mb-0",

      // JSON / Base64 syntax highlighting (syntaxHighlight() in tools-utils.js)
      "json-key",
      "json-string",
      "json-number",
      "json-boolean",
      "json-null",
      "json-pre",
      "json-output",

      // Diff checker (rows built via innerHTML)
      "diff-equal",
      "diff-add",
      "diff-remove",
      "diff-ln",
      "diff-code",

      // Regex tester (match highlights via innerHTML)
      "regex-match",

      // Password generator (bulk list via innerHTML)
      "bulk-copy",

      // Background remover (spinner injected via innerHTML)
      "spinner-border",
      "spinner-border-sm",

      // Bootstrap progress bar classes toggled via classList
      "progress-bar-animated",

      // Navbar toggle (mediumish.js classList.toggle)
      "show",
    ],

    // Patterns for class families that may be generated dynamically
    greedy: [
      // Rouge syntax highlighting: single/two-letter classes like .c, .k, .err, .gd
      // These are generated by Jekyll/Rouge and referenced in _syntax.scss
      /^highlight$/,
    ],
  },

  // Only report on our custom selectors, not Bootstrap (which is loaded from CDN)
  // The compiled .audit/*.css files only contain our custom SCSS output.
  rejected: true,
  rejectedCss: ".audit/rejected.css",
};
